### ISSUE TITLE
every time initial folder

### ISSUE THREAD

**Issue by grishok99** [cobaltCorsair/EBT_films_dose#4]
Often, when you process several films, you need to choose a new directory where the images are located each time . It will be very cool if the directory with the previous image is selected automatically.

**Comment by mr-xak** [comment]
Might lead to #8 in specific cases for storing last accessed folder across application runs. Developers are welcomed to #10

**Comment by cobaltCorsair** [comment]
This feature is implemented, but we encountered an unforeseen error related to running the compiled version on a network drive. It is necessary to open a new issue to solve this problem.

**Comment by cobaltCorsair** [comment]
This feature is implemented, but we encountered an unforeseen error related to running the compiled version on a network drive. It is necessary to open a new issue to solve this problem.
